server:
  port: 8080

sentry:
  dsn: ""
  environment: "production"
  # It is recommended to lower this value from the default of 1.0 on production
  traces-sample-rate: 1.0

spring:
  application:
    name: "OSC-Web"

osc-web:
  announcements:
    - "Welcome to the Open Shop Channel website!"
  base-url: "http://localhost:8080"
  enable-events: false
  repoman-host: "https://hbb1.oscwii.org"

management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate: WARN
    # org.springframework.beans: TRACE